pipeline {
    agent any

    tools {
        maven "3.6.3" // You need to add a maven with name "3.6.0" in the Global Tools Configuration page
    }
    stages {
        stage("Build") {
            steps {
                sh "mvn -version"
                sh "ls"
                dir('authSvc') {
                    sh "ls"
                    sh "mvn clean install"
                }
            }
        }
        stage("Dockerizing") {
            steps {
                docker.image('maven:3.6.3-jdk-8').inside {
                  git 'https://github.com/xzacharb/invoices.git'
                  dir('authSvc') {
                        sh "ls"
                        sh "mvn clean install"
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}